workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: latest
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: EAS build for iOS
        script: npx eas build --platform ios --non-interactive
    artifacts:
      - build/**/*
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID