workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      groups:
        - group
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
        APPLE_ID: $APPLE_ID
        APP_STORE_CONNECT_PASSWORD: $APP_STORE_CONNECT_PASSWORD
      node: latest
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: EAS build for iOS
        script: npx eas build --platform ios --non-interactive
    artifacts:
      - build/**/*
    publishing:
      app_store_connect:
        apple_id: lordlamberino@gmail.com
        password: yhvp-segf-vykk-uekn